# Generated by Django 5.2 on 2025-07-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='facture_client',
            new_name='FactureClient',
        ),
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-date_ajout']},
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='tate_ajout',
            new_name='date_ajout',
        ),
    ]
